### ISSUE TITLE
Failed to load the atomize-d package

### ISSUE THREAD

**Issue by gedaiu** [Pure-D/atomize-d#26]
[Enter steps to reproduce below:]

1. install plugin
2. run atom

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [atomize-d](https://github.com/Vild/atomize-d) package, v0.1.0

### Stack Trace

Failed to load the atomize-d package

```
At Cannot find module 'semver'

Error: Cannot find module 'semver'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/gedaiu/.atom/packages/atomize-d/lib/dub-config.coffee:3:10)
    at Object.<anonymous> (/Users/gedaiu/.atom/packages/atomize-d/lib/dub-config.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-dlang, v1.1.2
atomize-d, v0.1.0
ember-cli-helper, v0.9.0
jshint, v1.8.3
linter, v1.11.2
linter-dscanner, v0.2.3
linter-js-yaml, v1.2.4
linter-jshint, v1.2.1
linter-scss-lint, v2.4.0
pigments, v0.19.0
tested, v0.5.0
tool-bar, v0.1.9
trailing-spaces, v0.3.2

# Dev
linter-dscanner, v0.2.3
```

**Comment by Vild** [comment]
Please run `apm install` in the atomize-d directory.
Or use these updated install instructions
>git clone https://github.com/Vild/Atomize-D ~/.atom/packages/atomize-d
>cd ~/.atom/packages/atomize-d
>apm install

**Comment by gedaiu** [comment]
it still does not work

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.2
**Thrown From**: [atomize-d](https://github.com/Vild/atomize-d) package, v0.1.0


### Stack Trace

Uncaught SyntaxError: Unexpected token }

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fgedaiu%2Fworkspace%2Fproject-manager%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%7D%5D%2C%22windowInitializationScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22appVersion%22%3A%221.2.4%22%2C%22shellLoadTime%22%3A378%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fgedaiu%2Fworkspace%2Fproject-manager%22%5D%7D:16

SyntaxError: Unexpected token }
    at Object.parse (native)
    at /Users/gedaiu/.atom/packages/atomize-d/lib/dub-config.coffee:42:21
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-dlang, v1.1.2
atomize-d, v0.1.0
ember-cli-helper, v0.9.0
jshint, v1.8.3
linter, v1.11.3
linter-dscanner, v0.2.3
linter-js-yaml, v1.2.4
linter-jshint, v1.2.1
linter-scss-lint, v2.4.0
pigments, v0.19.1
tested, v0.5.0
tool-bar, v0.1.9
trailing-spaces, v0.3.2

# Dev
linter-dscanner, v0.2.3
```

**Comment by Vild** [comment]
Looks like there is something wrong with your dub.json

**Comment by WebFreak001** [comment]
Should work in new workspace-d branch now
